In [1]:
import numpy as np
import pandas as pd

In [2]:
matches = pd.read_csv("./data/match.csv")
teams = pd.read_csv("./data/team.csv")
team_attributes = pd.read_csv("./data/team_attributes.csv")

In [3]:
print("LENGTH MATCHES:  ",len(matches))
print("LENGTH TEAMS:  ",len(teams))
print("LENGTH TEAM ATTRIBUTES", len(team_attributes))

LENGTH MATCHES:   25979
LENGTH TEAMS:   299
LENGTH TEAM ATTRIBUTES 1458

In [4]:
#Finding teams which don't have attributes and removing their matches from the matches table
for team in teams['team_api_id'].unique():
    if team not in team_attributes['team_api_id'].unique():
        home = matches[matches['home_team_api_id'] == team].index
        away = matches[matches['away_team_api_id'] == team].index
        matches.drop(home, inplace = True)
        matches.drop(away, inplace = True)

In [5]:
attributes_notna = team_attributes[team_attributes['buildUpPlayDribbling'].notna()]
attributes_notna[attributes_notna['buildUpPlayDribblingClass'] == 'Little'].mean()

# All NaN values are in 'buildUpPlayDribbling' column when 'buildUpPlayDribblingClass' == 'Little'
# Average 'buildUpPlayDribbling' value is 30 when 'buildUpPlayDribblingClass' == 'Little'
team_attributes.fillna(30, inplace = True)
# Dropping categorical values
for col in team_attributes.columns:
    if "Class" in col:
        team_attributes.drop(columns = col, inplace = True)
team_attributes.drop(columns = 'team_fifa_api_id', inplace = True)

In [6]:
#Creating new column for results, since we don't care about specific goal numbers, but only match outcome
mat=matches.drop(columns=matches.columns[11:])
mat = mat.drop(columns=mat.columns[1:3])
ma = mat.drop(columns=mat.columns[2:4])
ma["result"]=ma["home_team_goal"] - ma["away_team_goal"]
ma.loc[ma["result"]>0,"result"] = 1
ma.loc[ma["result"]<0,"result"] = -1
ma.loc[ma["result"]==0,"result"] = 0
print(ma.groupby("result")["id"].count())
ma.rename(columns={'home_team_api_id': 'home_team'},inplace=True)
ma.rename(columns={'away_team_api_id': 'away_team'},inplace=True)
ma

result
-1     7363
 0     6510
 1    11756
Name: id, dtype: int64

,id,season,match_api_id,home_team,away_team,home_team_goal,away_team_goal,result
0,1,2008/2009,492473,9987,9993,1,1,0
1,2,2008/2009,492474,10000,9994,0,0,0
2,3,2008/2009,492475,9984,8635,0,3,-1
3,4,2008/2009,492476,9991,9998,5,0,1
5,6,2008/2009,492478,8203,8342,1,1,0
...,...,...,...,...,...,...,...,...
25972,25973,2015/2016,1992089,10243,10191,3,3,0
25974,25975,2015/2016,1992091,10190,10191,1,0,1
25975,25976,2015/2016,1992092,9824,10199,1,2,-1
25976,25977,2015/2016,1992093,9956,10179,2,0,1
25978,25979,2015/2016,1992095,10192,9931,4,3,1

In [7]:
# converting dates in team_attributes table to seasons
# xx-05-31 is last games of season
def convert_to_season(date_in_some_format):
    date = date_in_some_format[0:10]
    year = int(date[0:4])
    month = int(date[6:7])
    day = int(date[8:9])
    if month < 6:
        season = str(year-1)+'/'+str(year)
    else:
        season = str(year)+'/'+str(year+1)
    return str(season)

team_attributes['date'] = team_attributes['date'].apply(convert_to_season)
team_attributes.rename(columns={'date': 'season(TA)'},inplace=True)
team_attributes

,id,team_api_id,season(TA),buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth
0,1,9930,2009/2010,60,30.0,50,60,65,55,50,55,45
1,2,9930,2014/2015,52,48.0,56,54,63,64,47,44,54
2,3,9930,2015/2016,47,41.0,54,54,63,64,47,44,54
3,4,8485,2009/2010,70,30.0,70,70,70,70,60,70,70
4,5,8485,2010/2011,47,30.0,52,53,48,52,47,47,52
...,...,...,...,...,...,...,...,...,...,...,...,...
1453,1454,10000,2010/2011,52,30.0,52,52,48,53,46,48,53
1454,1455,10000,2011/2012,54,30.0,51,47,52,50,44,55,53
1455,1456,10000,2013/2014,54,30.0,51,47,52,32,44,58,37
1456,1457,10000,2014/2015,54,42.0,51,47,52,32,44,58,37
1457,1458,10000,2015/2016,54,42.0,51,47,52,32,44,58,37

In [8]:
#Merging team_attributes table into matches table so that every match has information about home and away team.
new_df = pd.merge(ma, team_attributes,left_on="home_team", right_on="team_api_id", how = "left").drop(columns=["id_y"])
new_df=new_df.drop(columns=["id_x"])
for col in team_attributes.columns[1:]:
    new_df["home_team "+col]=new_df[col]
    new_df=new_df.drop(columns=[col])
    
new_df = pd.merge(new_df, team_attributes,left_on="away_team", right_on="team_api_id", how = "left").drop(columns=["id"])
for col in team_attributes.columns[1:]:
    new_df["away_team "+col]=new_df[col]
    new_df=new_df.drop(columns=[col])
    
pd.set_option("display.max_rows", 10, "display.max_columns", None)
new_df

,season,match_api_id,home_team,away_team,home_team_goal,away_team_goal,result,home_team team_api_id,home_team season(TA),home_team buildUpPlaySpeed,home_team buildUpPlayDribbling,home_team buildUpPlayPassing,home_team chanceCreationPassing,home_team chanceCreationCrossing,home_team chanceCreationShooting,home_team defencePressure,home_team defenceAggression,home_team defenceTeamWidth,away_team team_api_id,away_team season(TA),away_team buildUpPlaySpeed,away_team buildUpPlayDribbling,away_team buildUpPlayPassing,away_team chanceCreationPassing,away_team chanceCreationCrossing,away_team chanceCreationShooting,away_team defencePressure,away_team defenceAggression,away_team defenceTeamWidth
0,2008/2009,492473,9987,9993,1,1,0,9987,2009/2010,45,30.0,45,50,35,60,70,65,70,9993,2009/2010,35,30.0,35,45,40,50,70,70,70
1,2008/2009,492473,9987,9993,1,1,0,9987,2009/2010,45,30.0,45,50,35,60,70,65,70,9993,2010/2011,47,30.0,37,54,64,67,33,34,48
2,2008/2009,492473,9987,9993,1,1,0,9987,2009/2010,45,30.0,45,50,35,60,70,65,70,9993,2011/2012,55,30.0,55,47,46,49,45,46,50
3,2008/2009,492473,9987,9993,1,1,0,9987,2009/2010,45,30.0,45,50,35,60,70,65,70,9993,2013/2014,47,30.0,39,38,64,49,45,46,67
4,2008/2009,492473,9987,9993,1,1,0,9987,2010/2011,66,30.0,52,65,66,51,48,47,54,9993,2009/2010,35,30.0,35,45,40,50,70,70,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781620,2015/2016,1992095,10192,9931,4,3,1,10192,2015/2016,52,56.0,64,39,66,46,44,34,50,9931,2010/2011,46,30.0,40,51,54,49,38,53,55
781621,2015/2016,1992095,10192,9931,4,3,1,10192,2015/2016,52,56.0,64,39,66,46,44,34,50,9931,2011/2012,61,30.0,46,66,66,54,47,58,53
781622,2015/2016,1992095,10192,9931,4,3,1,10192,2015/2016,52,56.0,64,39,66,46,44,34,50,9931,2013/2014,61,30.0,46,66,66,54,47,58,53
781623,2015/2016,1992095,10192,9931,4,3,1,10192,2015/2016,52,56.0,64,39,66,46,44,34,50,9931,2014/2015,61,63.0,46,66,66,54,47,58,53
781624,2015/2016,1992095,10192,9931,4,3,1,10192,2015/2016,52,56.0,64,39,66,46,44,34,50,9931,2015/2016,61,63.0,46,66,66,54,47,58,53

In [9]:
team_attributes.sort_values(by='season(TA)', ascending=True, inplace = True)
team_attributes

,id,team_api_id,season(TA),buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth
0,1,9930,2009/2010,60,30.0,50,60,65,55,50,55,45
426,427,8674,2009/2010,41,30.0,32,40,47,69,30,30,30
1147,1148,10189,2009/2010,65,30.0,55,55,70,70,70,45,70
419,420,8722,2009/2010,55,30.0,65,65,40,60,45,55,70
418,419,8596,2009/2010,70,30.0,70,60,70,70,60,70,70
...,...,...,...,...,...,...,...,...,...,...,...,...
443,444,9908,2015/2016,50,39.0,54,55,64,28,54,58,47
444,445,9824,2015/2016,53,32.0,56,38,53,46,42,33,58
1123,1124,9853,2015/2016,58,55.0,52,48,64,52,48,51,49
1280,1281,8586,2015/2016,47,46.0,40,41,41,63,63,54,56
1457,1458,10000,2015/2016,54,42.0,51,47,52,32,44,58,37

#### The follwoing cell takes ~ 3 hours to complete

In [10]:
    #Leaves only rows with most appropriate team versions in merged dataframe and saves it to csv file
    # NB! This cell takes roughly 3 hours to finish it's work

    team_attributes.sort_values(by='season(TA)', ascending=True, inplace = True)
    for index in ma.index:
        match_id = ma['match_api_id'][index]
        season = ma['season'][index]
        season_start = int(season[0:4])
        home = ma['home_team'][index]
        away = ma['away_team'][index]
        home_atts = team_attributes[team_attributes['team_api_id'] == home]
        away_atts = team_attributes[team_attributes['team_api_id'] == away]
        home_season = ""
        away_season = ""
        for indx, i in enumerate(home_atts['season(TA)']):
            start_year = int(i[0:4])
            # if complete match
            if start_year == season_start:
                home_season = i
                break
            # if next entry matches (so next if statement isn't called incorrectly)
            elif (indx+1 < len(list(home_atts['season(TA)']))) and (int(list(home_atts['season(TA)'])[indx+1][0:4]) == season_start):
                home_season = list(home_atts['season(TA)'])[indx+1]
                break
            # previous season's team also in current season when no team marked for current season
            elif int(i[5:9]) == season_start:
                home_season = i
                break
            # earliest team version in team_attributes applied if no other appropriate value can be given
            elif start_year > season_start:
                home_season = i
                break
            elif start_year < season_start:
                home_season = i
            
        for indx, i in enumerate(away_atts['season(TA)']):
            start_year = int(i[0:4])
            if start_year == season_start:
                away_season = i
                break
            elif (indx+1 < len(list(away_atts['season(TA)']))) and (int(list(away_atts['season(TA)'])[indx+1][0:4]) == season_start):
                away_season = list(away_atts['season(TA)'])[indx+1]
                break
            elif int(i[5:9]) == season_start:
                away_season = i
                break
            elif start_year > season_start:
                away_season = i
                break
            elif start_year < season_start:
                away_season = i
                
        new_matches = new_df[new_df['match_api_id'] == match_id].index
        correct = new_df.loc[(new_df['match_api_id'] == match_id) & (new_df['home_team season(TA)'] == home_season) & (new_df['away_team season(TA)'] == away_season)]
        new_df.drop(new_matches, inplace = True)
        new_df = new_df.append(correct, ignore_index=True)
    new_df.to_csv("./data/data3.csv")

In [11]:
        #testing the filtering done in the cell above.
        team_attributes.sort_values(by='season(TA)', ascending=True, inplace = True)
        match_id = 1677186
        season = "2013/2014"
        season_start = int(season[0:4])
        print(season_start)
        home_atts = team_attributes[team_attributes['team_api_id'] == 9989]
        away_atts = team_attributes[team_attributes['team_api_id'] == 8573]
        home_season = ""
        away_season = ""
        for indx, i in enumerate(home_atts['season(TA)']):
            indx = 11111
            print(len(list(home_atts['season(TA)'])))
            start_year = int(i[0:4])
            if start_year == season_start:
                home_season = i
                print('h_1')
                break
            elif (indx+1 < len(list(home_atts['season(TA)']))) and (int(list(home_atts['season(TA)'])[indx+1][0:4]) == season_start):
                home_season = list(home_atts['season(TA)'])[indx+1]
                print('h_2')
                break
            elif int(i[5:9]) == season_start:
                home_season = i
                print('h_3')
                break
            elif start_year > season_start:
                home_season = i
                print('h_4')
                break
            elif start_year < season_start:
                home_season = i
                print('h_5')
            
        for indx, i in enumerate(away_atts['season(TA)']):
            start_year = int(i[0:4])
            print(len(list(away_atts['season(TA)'])))
            if start_year == season_start:
                away_season = i
                print('a_1')
                break
            elif (indx+1 < len(list(away_atts['season(TA)']))) and (int(list(away_atts['season(TA)'])[indx+1][0:4]) == season_start):
                away_season = list(away_atts['season(TA)'])[indx+1]
                print('a_2')
                break
            elif int(i[5:9]) == season_start:
                away_season = i
                print('a_3')
                break
            elif start_year > season_start:
                away_season = i
                print('a_4')
                break
            elif start_year < season_start:
                away_season = i
                print('a_5')
                
        print(home_season)
        print(away_season)
        new_matches = new_df[new_df['match_api_id'] == match_id].index
        correct = new_df.loc[(new_df['match_api_id'] == match_id) & (new_df['home_team season(TA)'] == home_season) & (new_df['away_team season(TA)'] == away_season)]
        new_df.drop(new_matches, inplace = True)
        new_df = new_df.append(correct, ignore_index=True)
new_df.loc[new_df['match_api_id'] == 1677186]

2013
5
h_5
5
h_5
5
h_1
2
a_4
2013/2014
2014/2015

,season,match_api_id,home_team,away_team,home_team_goal,away_team_goal,result,home_team team_api_id,home_team season(TA),home_team buildUpPlaySpeed,home_team buildUpPlayDribbling,home_team buildUpPlayPassing,home_team chanceCreationPassing,home_team chanceCreationCrossing,home_team chanceCreationShooting,home_team defencePressure,home_team defenceAggression,home_team defenceTeamWidth,away_team team_api_id,away_team season(TA),away_team buildUpPlaySpeed,away_team buildUpPlayDribbling,away_team buildUpPlayPassing,away_team chanceCreationPassing,away_team chanceCreationCrossing,away_team chanceCreationShooting,away_team defencePressure,away_team defenceAggression,away_team defenceTeamWidth
25658,2013/2014,1677186,9989,8573,0,2,-1,9989,2013/2014,69,30.0,58,56,52,61,38,49,65,8573,2014/2015,52,49.0,54,45,42,53,42,47,44

In [34]:
merged = pd.read_csv("./data/data3.csv")

In [35]:
merged_final = merged.drop(columns = ['Unnamed: 0', 'match_api_id', 'home_team team_api_id', 'away_team team_api_id'])

In [36]:
#converting seasons to their start year as integers so that they are usable in model
def convert_to_year(date_in_some_format):
    year = date_in_some_format[0:4]
    return int(year)

merged_final['season'] = merged_final['season'].apply(convert_to_year)
merged_final.rename(columns={'season': 'year'},inplace=True)
merged_final['home_team season(TA)'] = merged_final['home_team season(TA)'].apply(convert_to_year)
merged_final.rename(columns={'home_team season(TA)': 'home_team year'},inplace=True)
merged_final['away_team season(TA)'] = merged_final['away_team season(TA)'].apply(convert_to_year)
merged_final.rename(columns={'away_team season(TA)': 'away_team year'},inplace=True)
merged_final

,year,home_team,away_team,home_team_goal,away_team_goal,result,home_team year,home_team buildUpPlaySpeed,home_team buildUpPlayDribbling,home_team buildUpPlayPassing,home_team chanceCreationPassing,home_team chanceCreationCrossing,home_team chanceCreationShooting,home_team defencePressure,home_team defenceAggression,home_team defenceTeamWidth,away_team year,away_team buildUpPlaySpeed,away_team buildUpPlayDribbling,away_team buildUpPlayPassing,away_team chanceCreationPassing,away_team chanceCreationCrossing,away_team chanceCreationShooting,away_team defencePressure,away_team defenceAggression,away_team defenceTeamWidth
0,2008,9987,9993,1,1,0,2009,45,30.0,45,50,35,60,70,65,70,2009,35,30.0,35,45,40,50,70,70,70
1,2008,10000,9994,0,0,0,2009,65,30.0,60,60,40,50,70,60,70,2009,60,30.0,60,50,40,50,65,65,70
2,2008,9984,8635,0,3,-1,2009,45,30.0,35,70,45,55,65,60,70,2009,50,30.0,35,70,50,60,70,50,70
3,2008,9991,9998,5,0,1,2009,70,30.0,65,60,50,60,45,50,40,2011,50,30.0,50,55,48,46,46,45,47
4,2008,8203,8342,1,1,0,2009,65,30.0,60,50,40,50,60,70,60,2009,35,30.0,40,45,50,45,60,70,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25654,2015,10243,10191,3,3,0,2015,62,49.0,46,47,50,54,47,43,56,2015,58,59.0,35,64,36,66,47,45,53
25655,2015,10190,10191,1,0,1,2015,52,46.0,48,39,39,37,40,36,52,2015,58,59.0,35,64,36,66,47,45,53
25656,2015,9824,10199,1,2,-1,2015,53,32.0,56,38,53,46,42,33,58,2015,63,51.0,51,54,40,66,48,53,50
25657,2015,9956,10179,2,0,1,2015,50,60.0,54,52,54,46,36,43,47,2015,61,57.0,37,62,50,53,45,47,54
25658,2015,10192,9931,4,3,1,2015,52,56.0,64,39,66,46,44,34,50,2015,61,63.0,46,66,66,54,47,58,53

In [37]:
merged_final.to_csv("./data/data_model_B.csv")